# Generated by Django 2.2.1 on 2019-05-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190511_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='avatar',
        ),
    ]
