# Generated by Django 2.2.1 on 2019-05-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190514_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default-avatar.jpg', upload_to='images/%Y%m%d/'),
        ),
    ]
