# Generated by Django 2.2.1 on 2019-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190515_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, default='default-post.png', upload_to='images/%Y%m%d/'),
        ),
    ]
