# Generated by Django 2.2.1 on 2019-05-22 16:26

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20190519_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(blank=True),
        ),
    ]
