# Generated by Django 2.2.1 on 2019-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20190515_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.jpg', upload_to='avatar/%Y%m%d/'),
        ),
    ]
